TekkenGame/TekkenGame/Models/Personagens.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TekkenGame.Models
{
    public class Personagens
    {
        public Personagens()
        {
            ListaDeComentarios = new HashSet<Comentarios>();
            ListaDeJogos = new HashSet<Jogos>();
        }

        [Key]
        public int ID { get; set; }
        
        public string Nome { get; set; }
        
        public string Origem { get; set; }
        
        [DisplayName("Tipo de luta")]
        public string TipoLuta { get; set; }
        
        public string Fotografia { get; set; }
        
        public string Biografia { get; set; }

        [DisplayName("Lista de comentários")]
        public virtual ICollection<Comentarios> ListaDeComentarios { get; set; }

        [DisplayName("Lista de jogos")]
        public virtual ICollection<Jogos> ListaDeJogos { get; set; }
    }
}

TekkenGame/TekkenGame/Controllers/PersonagensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TekkenGame.Models;

namespace TekkenGame.Controllers
{
    public class PersonagensController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Personagens
        public ActionResult Index()
        {
            // obter a lista das personagens por ordem alfabética
            // em SQL: SELECT * FROM Personagens ORDER BY Nome;
            var listaDePersonagens = db.Personagens.ToList().OrderBy(a => a.Nome);

            return View(listaDePersonagens);
        }

        // GET: Personagens/Details/5
        public ActionResult Details(int? id)
        {
            // se se escrever 'int?' é possível não fornecer o valor para o ID e não há erro

            // proteção para o caso de não ter sido fornecido um ID válido
            if (id == null)
            {
                // se não houve ID, volta ao Index
                return RedirectToAction("Index");
            }

            // procura na BD a personagem cujo ID foi fornecido
            Personagens personagens = db.Personagens.Find(id);

            // se a personagem não for encontrada

            if (personagens == null)
            {
                // redireciona ao Index
                return RedirectToAction("Index");
            }

            // entrega à View os dados da personagem encontrada
            return View(personagens);
        }

        [Authorize(Roles = "Admin")]
        // GET: Personagens/Create
        public ActionResult Create()
        {
            //gerar a lista de Jogos associados à Personagem
            ViewBag.ListaDeJogos = db.Jogos.OrderBy(b => b.Titulo).ToList();
            // apresenta a View para se inserir uma nova Personagem
            return View();
        }

        // POST: Personagens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Origem,TipoLuta,Fotografia,Biografia")] Personagens personagem, HttpPostedFileBase uploadFotografia, string[] checkBoxJogos)
        {
            // avalia se o array com a lista de Jogos associados
            // à Personagem é nula ou não
            if (checkBoxJogos == null)
            {
                ModelState.AddModelError("", "Necessita escolher pelo menos um jogo para associar à Personagem");
                ViewBag.ListaDeJogos = db.Jogos.OrderBy(a => a.Titulo).ToList();
                return View(personagem);
            }

            // criar uma lista
            List<Jogos> ListaDeJogosEscolhidas = new List<Jogos>();
            foreach (string item in checkBoxJogos)
            {
                // procurar Jogo
                Jogos jogos = db.Jogos.Find(Convert.ToInt32(item));
                // adicioná-lo à lista de jogos
                ListaDeJogosEscolhidas.Add(jogos);
            }

            personagem.ListaDeJogos = ListaDeJogosEscolhidas;

            // escrever os dados de uma nova Personagem na BD
            // especificar o ID da nova Personagem através de um TRY/CATCH
            int idNovaPersonagem = 0;

            try
            {
                // vai à BD, depois à tabela das Personagens e calcula o ID máximo
                idNovaPersonagem = db.Personagens.Max(a => a.ID) + 1;
            }
            catch (Exception)
            {
                idNovaPersonagem = 1;
            }

            // guardar o ID da nova Personagem
            personagem.ID = idNovaPersonagem;

            // especificar o nome do ficheiro
            string nomeImagem = "Personagem_" + idNovaPersonagem + ".jpg";

            // variável auxiliar
            string path = "";

            // validar se a imagem foi fornecida
            if (uploadFotografia != null)
            {
                // o ficheiro foi fornecido
                // criar o caminho completo até ao sítio onde o ficheiro será guardado
                path = Path.Combine(Server.MapPath("~/ImagemPers/"), nomeImagem);

                // guardar o nome do ficheiro na BD
                personagem.Fotografia = nomeImagem;
            }
            else
            {
                // não foi fornecido um ficheiro
                // gerar uma mensagem de erro
                ModelState.AddModelError("", "Não foi fornecida uma imagem.");

                // devolver o controlo à View
                return View(personagem);
            }

            // ModelState.IsValid -> confronta os dados fornecidos da View com as exigências do Modelo
            if (ModelState.IsValid)
            {
                // adicionar a nova personagem à BD
                db.Personagens.Add(personagem);
                // faz 'commit' às alterações
                db.SaveChanges();

                // escrever o ficheiro com a fotografia no disco rígido, na pasta 'imagens'
                uploadFotografia.SaveAs(path);

                // retorna ao index
                return RedirectToAction("Index");
            }

            return View(personagem);
        }

        [Authorize(Roles = "Admin")]
        // GET: Personagens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                // se o ID não for encontrado ou não existir, volta ao Index
                return RedirectToAction("Index");
            }

            // procura na BD a personagem cujo ID foi fornecido
            Personagens personagem = db.Personagens.Find(id);

            // proteção para caso de não ter sido encontrado qualquer Personagem que tenha o ID fornecido
            if (personagem == null)
            {
                // retorna para o index
                return RedirectToAction("Index");
            }

            //gerar a lista de Jogos associados à Personagem
            ViewBag.ListaDeJogos = db.Jogos.OrderBy(b => b.Titulo).ToList();

            return View(personagem);
        }

        // POST: Personagens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Origem,TipoLuta,Fotografia,Biografia")] Personagens personagem, HttpPostedFileBase uploadFotografia, string[] checkBoxJogos)
        {
            // ler da BD o objeto que se pretende editar
            var personagens = db.Personagens.Include(b => b.ListaDeJogos).Where(b => b.ID == personagem.ID).SingleOrDefault();

            // avaliar se os dados são 'bons'
            if (ModelState.IsValid)
            {
                personagens.Nome = personagem.Nome;
                personagens.Origem = personagem.Origem;
                personagens.TipoLuta = personagem.TipoLuta;
                personagens.Fotografia = personagem.Fotografia;
                personagens.Biografia = personagem.Biografia;
            }
            else
            {
                // gerar a lista de personagens associados ao Jogo
                ViewBag.ListaDeJogos = db.Jogos.OrderBy(b => b.Titulo).ToList();
                return View(personagem);
            }

            // tentar fazer o UPDATE
            if (TryUpdateModel(personagens, new string[] { nameof(personagens.Nome), nameof(personagens.Origem), nameof(personagens.TipoLuta), nameof(personagens.Fotografia), nameof(personagens.Biografia), nameof(personagens.ListaDeJogos)}))
            {
                // obter lista de personagens
                var jogos = db.Jogos.ToList();

                if (checkBoxJogos != null)
                {
                    foreach (var item in jogos)
                    {
                        if (checkBoxJogos.Contains(item.ID.ToString()))
                        {
                            if (!personagens.ListaDeJogos.Contains(item))
                            {
                                personagens.ListaDeJogos.Add(item);
                            }
                        }
                        else
                        {
                            // caso exista associação para uma opção que não foi escolhida,
                            // remove-se essa associação
                            personagens.ListaDeJogos.Remove(item);
                        }
                    }
                }
                else
                {
                    // não existem opções escolhidas!
                    // vamos eliminar todas as associações
                    foreach (var item in jogos)
                    {
                        if (personagens.ListaDeJogos.Contains(item))
                        {
                            personagens.ListaDeJogos.Remove(item);
                        }
                    }
                }

                // guardar as alterações
                db.SaveChanges();

                // devolver controlo à View
                return RedirectToAction("Index");
            }

            // se cheguei aqui, é porque alguma coisa correu mal
            ModelState.AddModelError("", "Alguma coisa correu mal...");

            //gerar a lista de personagens associados ao Jogo
            ViewBag.ListaDeJogos = db.Personagens.OrderBy(r => r.Nome).ToList();

            string path = "";

            if (uploadFotografia == null)
            {
                db.Entry(personagem).State = EntityState.Modified;

                db.SaveChanges();
                ViewBag.Jogos = db.Jogos;
                return RedirectToAction("Index");
            }
            else
            {

TekkenGame/TekkenGame/Views/Personagens/Create.cshtml
@model TekkenGame.Models.Personagens

@{
    ViewBag.Title = "Criar Personagem";
}

<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>


<div style="color:red; font-family:'Lucida Console'; font-size:48px; margin-top:30px;">Criar personagem</div>


@using (Html.BeginForm("Create",
                        "Personagens",
                        FormMethod.Post,
                        new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Origem, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Origem, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Origem, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.TipoLuta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.TipoLuta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TipoLuta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @* adição do objeto para fazer o file upload de uma fotografia *@
            <input type="file" name="uploadFotografia"
                   syle="color:blue" accept=".jpg" />
            @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Biografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Biografia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Biografia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span class="control-label col-md-2">Jogos associados à Personagem:</span>
        <div class="col-md-10">
            @{ string selected = "";}
            @foreach (var item in ViewBag.ListaDeJogos)
            {
                <input type="checkbox" name="checkBoxJogos" value="@item.ID" @selected /> @item.Titulo
                <br />
            }
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Criar" class="button" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar à lista de personagens", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TekkenGame/TekkenGame/Views/Personagens/Delete.cshtml
@model TekkenGame.Models.Personagens

@{
    ViewBag.Title = "Apagar personagem";
}

<
<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>

<div style="font-family: 'Lucida Console'; text-align: left;color: white; font-size: 32px;font-weight: bold;margin-top: 50px;">Tem a certeza que pretende apagar esta personagem da lista?</div>

<div class="alert alert-warning" style="font-family:'Lucida Console'">
    <strong>Atenção!</strong> Ao apagar esta personagem, todos os seus dados serão perdidos.
</div>
<div>
    @* HTML Helper para apresentar as mensagens de erro *@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="dl-horizontal">
        @*Imagem da Personagem a apagar*@
        <div>
            <a href="/Personagens/Details/@Model.ID">
                <img src="~/ImagemPers/@Model.Fotografia" width="250" height="260" />
            </a>
        </div>
        @*Nome da Personagem a apagar*@
        <div style="color:red; margin-left:265px; margin-top:-260px; font-family:'Lucida Console'; font-size:35px;">
            @Html.DisplayFor(model => model.Nome)
        </div>


    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="button" style="margin-left:260px; margin-top:129px; font-size:25px;" /> |
            @*Botão para voltar à lista de Jogos*@
        <div class="btn-group" role="group" style="margin-bottom:9px; padding-top:13px; padding-left: 0px;">
            <button type="button" class="button" onclick="location.href='@Url.Action("Details","Personagens",new { id=Model.ID })'">Voltar atrás</button>
            <button type="button" class="button" onclick="location.href='@Url.Action("Index","Personagens",new { id = Model.ID })'">Voltar para a lista de Personagens</button>
        </div>
        </div>
    }
</div>

TekkenGame/TekkenGame/Views/Personagens/Details.cshtml
@model TekkenGame.Models.Personagens

@{
    ViewBag.Title = "Detalhes da personagem";
}

@* imagem de fundo *@
<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>


<div style="margin-top: 40px; display: -webkit-flex; -webkit-align-items: center; display: flex;align-items: center;">
    @* imagem da personagem *@
    <div style="border:solid;border-color:black;">
        <a href="~/ImagemPers/@Model.Fotografia" target="_blank">
            <img src="~/ImagemPers/@Model.Fotografia" width="400" height="457" />
        </a>
    </div>

    <div style="height:400px">
        @* nome da personagem *@
        <div style="font-family: Arial; text-align: left;color: red; font-size: 50px;font-weight: bold;margin-top: -45px; margin-left: 18px;width: 100%;">
            @Html.DisplayFor(model => model.Nome)
        </div>

        @* origem da personagem *@
        <div style="font-family:Arial;font-size: 25px; color: red; font-weight: bold;padding-top: 20px; margin-left:20px;">Natural</div>
        <div style="font-family:Arial; font-size: 18px; color: black;text-align:justify; padding-top:-300px; margin-left:20px; color:white;">
            <b>@Html.DisplayFor(model => model.Origem)</b>
        </div>

        @*Tipo de Luta da Personagem*@
        <div style="font-family:Arial;font-size: 25px; color: red; font-weight: bold;padding-top: 20px; margin-left:20px;">Tipo de luta</div>
        <div style="font-family:Arial; font-size: 18px; color: black;text-align:justify; padding-top:-300px; margin-left:20px; color:white;">
            <b>@Html.DisplayFor(model => model.TipoLuta)</b>
        </div>

        @*Biografia da Personagem*@
        <div style="font-family:Arial;font-size: 25px; color: red; font-weight: bold;padding-top: 20px; margin-left:20px;">Biografia</div>
        <div style="font-family:'Lucida Console'; font-size: 16.5px; color: black;text-align:justify; margin-left:20px; color:white">
            @Html.DisplayFor(model => model.Biografia)
        </div>


    </div>

</div>
<div style="font-family:Arial;font-size: 25px; color: red; font-weight: bold; padding-top: 20px; margin-left:0px;">Jogos presentes</div>
<span>
    @if (Model.ListaDeJogos.Count() > 0)
    {
        foreach (var jogo in Model.ListaDeJogos)
        {
            <a href="~/Jogos/Details/@jogo.ID">
                <img src="~/ImagemLogo/@jogo.Logotipo" width="180" height="150" />
            </a>
        }
    }
</span>

@* botões de editar a personagem somente para o administrador *@
@if (User.IsInRole("Admin"))
{
    <div class="btn-group" role="group" style="margin-bottom:9px; padding-left: 758px;">
        <button type="button" class="button" onclick="location.href='@Url.Action("Edit","Personagens", new { id = Model.ID })'">Editar Personagem</button>
        <button type="button" class="button" onclick="location.href='@Url.Action("Delete","Personagens", new { id = Model.ID })'">Apagar Personagem</button>
    </div>
}

@* botão para voltar à lista de jogos *@
<div class="btn-group" role="group" style="margin-bottom:9px; padding-top:10px; padding-left: 805px;">
    <button type="button" class="button" onclick="location.href='@Url.Action("Index","Personagens",new { id = Model.ID })'">Voltar para a lista de Personagens</button>
</div>

TekkenGame/TekkenGame/Views/Personagens/Edit.cshtml
@model TekkenGame.Models.Personagens

@{
    ViewBag.Title = "Edit";
}

<style>
    @* imagem de fundo *@
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }
    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }
        .button:hover {
            background-color: #D3D3D3
        }
        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>

<div style="color:red; font-family:'Lucida Console'; font-size:48px; margin-top:30px;">Editar Personagem</div>


@using (Html.BeginForm("Edit", "Personagens", null, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Origem, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Origem, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Origem, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.TipoLuta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.TipoLuta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TipoLuta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            <a href="~/ImagemPers/@Model.Fotografia" target="_blank">
                <img src="~/ImagemPers/@Model.Fotografia" height="150" />
            </a>


            @Html.Hidden("Fotografia", Model.Fotografia)
            <input type="file" name="uploadFotografia"
                   style="color:blue;" accept=".jpg" ; />
            @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })


        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Biografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Biografia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Biografia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        <span class="control-label col-md-2">Jogos associados à Personagem:</span>
        <div class="col-md-10">
            @{ string selected = "";}
            @foreach (var item in ViewBag.ListaDeJogos)
            {
                selected = "";
                foreach (int opcaoID in Model.ListaDeJogos.Select(b => b.ID))
                {
                    if (item.ID == opcaoID) { selected = "checked"; }
                }
                <input type="checkbox" name="checkBoxJogos" value="@item.ID" @selected /> @item.Titulo
                <br />
            }
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="button" />
        </div>
    </div>
</div>

    @*Botão para voltar à lista de Personagens*@
<div class="btn-group" role="group" style="margin-bottom:9px; padding-left: 195px;">
    <button type="button" class="button" onclick="location.href='@Url.Action("Details","Personagens",new { id=Model.ID })'">Voltar atrás</button>
    <button type="button" class="button" onclick="location.href='@Url.Action("Index","Personagens",new { id = Model.ID })'">Voltar para a lista de Personagens</button>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TekkenGame/TekkenGame/Views/Personagens/Index.cshtml
@model IEnumerable<TekkenGame.Models.Personagens>

@{
    ViewBag.Title = "Personagens";
}

<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }
</style>

<div style="font-family: 'Lucida Console'; text-align: left;color: red; font-size: 40px;font-weight: bold; margin-left:220px; margin-top:40px;">
    Conheça todas as personagens!
</div>

<div style=" display:flex; flex-wrap:wrap; flex-direction:row; justify-content:space-around; align-content:center; margin-top:30px;">
    @foreach (var item in Model)
    {
        <div style="padding-top: 15px">
            <a href="~/Personagens/Details/@item.ID">
                <img src="~/ImagemPers/@item.Fotografia" width="200" height="210" />
            </a>
        </div>
     }
</div>
 

@if (User.IsInRole("Admin"))
{
    <div style="padding-top: 50px;  margin-left: 400px;">
        @Html.ActionLink("Adicionar nova personagem", "Create")
    </div>
}