TekkenGame/TekkenGame/Models/Jogos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TekkenGame.Models
{
    public class Jogos
    {
        public Jogos()
        {
            ListaDeComentarios = new HashSet<Comentarios>();
            ListaDePersonagens = new HashSet<Personagens>();
            ListaDePlataformas = new HashSet<Plataformas>();
        }

        [Key]
        public int ID { get; set; }
        
        [DisplayName("Título")]
        public string Titulo { get; set; }
       
        /// <summary>
        /// logotipo do jogo
        /// </summary>
        public string Logotipo { get; set; }
        
        /// <summary>
        /// imagem da capa do jogo
        /// </summary>
        public string Fotografia { get; set; }
       
        public string Resumo { get; set; }

        [DisplayName("Lista de comentários")]
        public virtual ICollection<Comentarios> ListaDeComentarios { get; set; }
        [DisplayName("Lista de personagens")]
        public virtual ICollection<Personagens> ListaDePersonagens { get; set; }
        [DisplayName("Lista de plataformas")]
        public virtual ICollection<Plataformas> ListaDePlataformas { get; set; }
    }
}

TekkenGame/TekkenGame/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using TekkenGame.Models;

namespace TekkenGame.Controllers
{
    public class ComentariosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comentarios
        public ActionResult Index()
        {
            var comentarios = db.Comentarios.Include(c => c.Jogo).Include(c => c.Utilizadores);
            return View(comentarios.ToList());
        }

        // GET: Comentarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Comentarios comentarios = db.Comentarios.Find(id);
            if (comentarios == null)
            {
                return RedirectToAction("Index");
            }
            return View(comentarios);
        }

        [Authorize(Roles = "Admin, Utilizador")]
        // GET: Comentarios/Create
        public ActionResult Create()
        {
            ViewBag.JogoFK = new SelectList(db.Jogos, "ID", "Titulo");
            ViewBag.UtilizadoresFK = new SelectList(db.Utilizadores, "ID", "UserName");
            return View();
        }

        // POST: Comentarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Texto,JogoFK")] Comentarios comentario, string Username)
        {

            int idNovoComentario = 0;
            try
            {
                // vai à BD, depois à tabela dos Jogos e calcula o ID máximo
                idNovoComentario = db.Comentarios.Max(a => a.ID) + 1;
            }
            catch (Exception)
            {
                idNovoComentario = 1;
            }

            // guardar o ID do novo Jogo
            comentario.ID = idNovoComentario;

            comentario.DataComentario = DateTime.Now;

            List<Utilizadores> todos = db.Utilizadores.ToList();
            foreach (Utilizadores u in todos)
            {
                if (u.UserName == Username)
                {
                    comentario.UtilizadoresFK = u.ID;
                    break;
                }
            }

            if (ModelState.IsValid)
            {
                db.Comentarios.Add(comentario);
                db.SaveChanges();
                return RedirectToAction("Details", "Jogos", new { ID = comentario.JogoFK });
            }

            ViewBag.JogoFK = new SelectList(db.Jogos, "ID", "Titulo", comentario.JogoFK);
            ViewBag.UtilizadoresFK = new SelectList(db.Utilizadores, "ID", "UserName", comentario.UtilizadoresFK);
            return RedirectToAction("Details", "Jogos", new { ID = comentario.JogoFK });
        }

        //[Authorize(Roles = "Admin, Utilizador")]
        // GET: Comentarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Jogos");
            }
            Comentarios comentario = db.Comentarios.Find(id);
            if (comentario == null)
            {
                return RedirectToAction("Index", "Jogos");
            }
            //---------------------------------------------------------------------
            if (comentario.Utilizadores.UserName.Equals(User.Identity.Name) )
            {
                return View(comentario);
            }

            // se aqui cheguei, é pq o user não tem autorização para editar o comentário

            ModelState.AddModelError("", "Não tem autorização para editar o comentário");

            return RedirectToAction("Index");
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Texto,DataComentario,JogoFK,UtilizadoresFK")] Comentarios comentario)
        {
            if (ModelState.IsValid)
            {
                comentario.DataComentario = DateTime.Now;
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();

                // reenviar o user para o jogo de onde o comentário diz respeito
                return RedirectToAction("Details", "Jogos", new { ID = comentario.JogoFK });
            }
       
            return View(comentario);
        }

        //GET: Comentarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Jogos");
            }
            Comentarios comentarios = db.Comentarios.Find(id);
            if (comentarios == null)
            {
                return RedirectToAction("Index", "Jogos");
            }
            return View(comentarios);
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comentarios comentario = db.Comentarios.Find(id);
            try
            {
                // remove o comentário da memória
                db.Comentarios.Remove(comentario);
                // commit na BD
                db.SaveChanges();
                // redirecionar para a página inicial
                return RedirectToAction("Details", "Jogos", new { ID = comentario.JogoFK });
            }
            catch (Exception)
            {
                // mensagem de erro
                ModelState.AddModelError("", "Não foi possível remover.");
            }
            return View(comentario);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TekkenGame/TekkenGame/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TekkenGame.Models;

namespace TekkenGame.Controllers
{
    public class JogosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jogos
        public ActionResult Index()
        {
            var listaDeJogos = db.Jogos.ToList().OrderBy(a => a.Titulo);

            return View(listaDeJogos);
        }

        // GET: Jogos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Jogos jogos = db.Jogos.Find(id);

            if (jogos == null)
            {
                return RedirectToAction("Index");
            }
            return View(jogos);
        }

        [Authorize(Roles = "Admin")]
        // GET: Jogos/Create
        public ActionResult Create()
        {
            // gerar a lista de Personagens associadas ao Jogo
            ViewBag.ListaDePersonagens = db.Personagens.OrderBy(b => b.Nome).ToList();
            // gerar a lista de Plataformas associadas ao Jogo
            ViewBag.ListaDePlataformas = db.Plataformas.OrderBy(b => b.Nome).ToList();
            return View();
        }

        // POST: Jogos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titulo,Logotipo,Resumo")] Jogos jogo, HttpPostedFileBase uploadFotografia, string[] checkBoxPersonagens, string[] checkBoxPlataformas)
        {
            /// avalia se o array com a lista de Personagens associadas
            /// ao Jogo é nula ou não
            if (checkBoxPersonagens == null)
            {
                ModelState.AddModelError("", "Necessita escolher pelo menos uma Personagem para associar ao Jogo");
                ViewBag.ListaDePersonagens = db.Personagens.OrderBy(a => a.Nome).ToList();
                return View(jogo);
            }

            // criar uma lista
            List<Personagens> ListaDePersonagensEscolhidas = new List<Personagens>();
            foreach (string item in checkBoxPersonagens)
            {
                // procurar Personagem
                Personagens persongens = db.Personagens.Find(Convert.ToInt32(item));
                // adicioná-lo à lista de personagens
                ListaDePersonagensEscolhidas.Add(persongens);
            }

            jogo.ListaDePersonagens = ListaDePersonagensEscolhidas;

            // ************************************************************************************************************************************

            /// avalia se o array com a lista de personagens associados
            /// ao Jogo é nula ou não
            if (checkBoxPlataformas == null)
            {
                ModelState.AddModelError("", "Necessita escolher pelo menos uma Personagem para associar ao Jogo");
                ViewBag.ListaDePlataformas = db.Plataformas.OrderBy(a => a.Nome).ToList();
                return View(jogo);
            }

            // criar uma lista
            List<Plataformas> ListaDePlataformasEscolhidas = new List<Plataformas>();
            foreach (string item in checkBoxPlataformas)
            {
                // procurar Personagem
                Plataformas plataformas = db.Plataformas.Find(Convert.ToInt32(item));
                // adicioná-lo à lista de plataformas
                ListaDePlataformasEscolhidas.Add(plataformas);
            }

            jogo.ListaDePlataformas = ListaDePlataformasEscolhidas;

            //***********************************************************************************************************************************
            int idNovoJogo = 0;
            try
            {
                // vai à BD, depois à tabela dos Jogos e calcula o ID máximo
                idNovoJogo = db.Jogos.Max(a => a.ID) + 1;
            }
            catch (Exception)
            {
                idNovoJogo = 1;
            }

            // guardar o ID do novo Jogo
            jogo.ID = idNovoJogo;

            // especificar o nome do ficheiro
            string nomeImagem = "Jogo_" + idNovoJogo + ".jpg";

            // variável aux
            string path = "";

            // validar se a imagem foi fornecida
            if (uploadFotografia != null)
            {
                // o ficheiro foi fornecido
                // criar o caminho completo até ao sítio onde o ficheiro será guardado
                path = Path.Combine(Server.MapPath("~/ImagemCapas/"), nomeImagem);

                jogo.Fotografia = nomeImagem;
            }
            else
            {
                // não foi fornecido qualquer ficheiro
                // gerar uma mensagem de erro
                ModelState.AddModelError("", "Não foi fornecida uma imagem.");

                // devolver o controlo à View
                return View(jogo);
            }

            if (ModelState.IsValid)
            {
                // add o novo Jogo à BD
                db.Jogos.Add(jogo);

                // faz 'commit' às alterações.
                db.SaveChanges();

                // escrever o ficheiro com a fotografia no disco rígido, na pasta 'imagens'
                uploadFotografia.SaveAs(path);
                return RedirectToAction("Index");
            }

            return View(jogo);
        }

        [Authorize(Roles = "Admin")]
        // GET: Jogos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            // procura na BD o jogo cujo ID foi fornecido
            Jogos jogo = db.Jogos.Find(id);

            // proteção para o caso de não ter sido encontrado qualquer Jogo que tenha o ID fornecido
            if (jogo == null)
            {
                return RedirectToAction("Index");
            }

            // gerar a lista de Personagens associadas ao Jogo 
            ViewBag.ListaDePersonagens = db.Personagens.OrderBy(b => b.Nome).ToList();
            // gerar a lista de Plataformas associadas ao Jogo
            ViewBag.ListaDePlataformas = db.Plataformas.OrderBy(b => b.Nome).ToList();

            return View(jogo);
        }

        // POST: Jogos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,Logotipo,Resumo,Fotografia")] Jogos jogo, HttpPostedFileBase uploadFotografia, string[] checkBoxPersonagens, string[] checkBoxPlataformas)
        {
            // ler da BD os dados existentes sobre o objeto que se pretende editar
            var vAnteriorDoJogo = db.Jogos.Include(b => b.ListaDePersonagens).Include(b => b.ListaDePlataformas).Where(b => b.ID == jogo.ID).SingleOrDefault();

            // avaliar se os dados são 'bons'
            if (ModelState.IsValid)
            {
                vAnteriorDoJogo.Titulo = jogo.Titulo;
                vAnteriorDoJogo.Resumo = jogo.Resumo;
                vAnteriorDoJogo.Fotografia = jogo.Fotografia;
            }
            else
            {
                // gerar a lista de personagens associados ao Jogo
                ViewBag.ListaDePersonagens = db.Personagens.OrderBy(b => b.Nome).ToList();
                // gerar a lista de Plataformas associadas ao Jogo
                ViewBag.ListaDePlataformas = db.Plataformas.OrderBy(b => b.Nome).ToList();
                return View(jogo);
            }

            // tentar fazer o UPDATE
            if (TryUpdateModel(vAnteriorDoJogo, new string[] { nameof(vAnteriorDoJogo.Titulo), nameof(vAnteriorDoJogo.Logotipo), nameof(vAnteriorDoJogo.Resumo), nameof(vAnteriorDoJogo.Fotografia), nameof(vAnteriorDoJogo.ListaDePersonagens) }))
            {
                //*****************************************************************************************************
                // processar as personagens
                //*****************************************************************************************************
                // obter lista de personagens
                var personagens = db.Personagens.ToList();

                if (checkBoxPersonagens != null)
                {
                    foreach (var item in personagens)
                    {
                        if (checkBoxPersonagens.Contains(item.ID.ToString()))
                        {
                            if (!vAnteriorDoJogo.ListaDePersonagens.Contains(item))
                            {
                                vAnteriorDoJogo.ListaDePersonagens.Add(item);
                            }
                        }
                        else
                        {
                            // caso exista associação para uma opção que não foi escolhida,
                            // remove-se essa associação
                            vAnteriorDoJogo.ListaDePersonagens.Remove(item);
                        }
                    }
                }
                else
                {
                    // não existem opções escolhidas!
                    // vamos eliminar todas as associações
                    foreach (var item in personagens)
                    {
                        if (vAnteriorDoJogo.ListaDePersonagens.Contains(item))
                        {
                            vAnteriorDoJogo.ListaDePersonagens.Remove(item);
                            

TekkenGame/TekkenGame/Views/Jogos/Create.cshtml
@model TekkenGame.Models.Jogos

@{
    ViewBag.Title = "Adicionar novo Jogo";
}

<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>

<div style="color:red; font-family:'Lucida Console'; font-size:48px; margin-top:30px;">Adicionar novo jogo</div>

@using (Html.BeginForm("Create", "Jogos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            <input type="file" name="uploadFotografia"
                   syle="color:blue" accept=".jpg" />
            @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="color:white; font-family:'Lucida Console'; font-size:17px;">
        @Html.LabelFor(model => model.Resumo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="margin-top:5px;">
            @Html.EditorFor(model => model.Resumo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Resumo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Criar" class="button" />
        </div>
    </div>


    <div class="form-group">
        <span class="control-label col-md-2">Plataformas associadas ao jogo:</span>
        <div class="col-md-10">
            @{ string selected = "";}
            @foreach (var item in ViewBag.ListaDePlataformas)
            {
                <input type="checkbox" name="checkBoxPlataformas" value="@item.ID" @selected /> @item.Nome
                <br />
            }
        </div>
    </div>

    <div class="form-group">
        <span class="control-label col-md-2">Personagens associadas ao jogo:</span>
        <div class="col-md-10">
            @foreach (var item in ViewBag.ListaDePersonagens)
            {
                <input type="checkbox" name="checkBoxPersonagens" value="@item.ID" @selected /> @item.Nome
                <br />
            }
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-success" />

        </div>
    </div>
</div>

}



<div>
    @Html.ActionLink("Voltar à lista de jogos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TekkenGame/TekkenGame/Views/Jogos/Delete.cshtml
@model TekkenGame.Models.Jogos

@{
    ViewBag.Title = "Apagar jogo";
}
<style>
    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>

<div style="font-family: 'Lucida Console'; text-align: left;color: white; font-size: 32px;font-weight: bold;margin-top: 50px;">Tem a certeza que pretende apagar este jogo da lista?</div>

@*Alerta*@
<div class="alert alert-warning" style="font-family:'Lucida Console'">
    <strong>Atenção!</strong> Ao apagar este jogo, todos os seus dados serão perdidos.
</div>

<div>
    <div class="dl-horizontal">
        @*Imagem do Jogo a apagar*@
        <div>
            <a href="/Jogos/Details/@Model.ID">
                <img src="~/imagemCapas/@Model.Fotografia" width="250" height="260" />
            </a>
        </div>
        @*Titulo do Jogo a apagar*@
        <div style="color:red; margin-left:265px; margin-top:-260px; font-family:'Lucida Console'; font-size:35px;">
            @Html.DisplayFor(model => model.Titulo)
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Apagar" class="button" style="margin-left:260px; margin-top:152px; font-size:25px;" /> |
                @* botão para voltar à lista de Jogos *@
            <div class="btn-group" role="group" style="margin-bottom:9px; padding-top:15px; padding-left: 0px;">
                <button type="button" class="button" onclick="location.href='@Url.Action("Details","Jogos",new { id=Model.ID })'">Voltar atrás</button>
                <button type="button" class="button" onclick="location.href='@Url.Action("Index","Jogos",new { id = Model.ID })'">Voltar para a lista de Jogos</button>
            </div>
            </div>
        }
    </div>
</div>

TekkenGame/TekkenGame/Views/Jogos/Details.cshtml
@model TekkenGame.Models.Jogos
@{
    ViewBag.Title = "Detalhes do jogo";
}
<style>

    body {
        background-image: url(../../Fundos/Fundo3.jpg);
    }

    .button {
        display: inline-block;
        padding: 10px 20px;
        font-size: 14px;
        cursor: pointer;
        text-align: center;
        font-family: 'Lucida Console';
        color: black;
        background-color: white;
        border: blue;
        border-radius: 12px;
        border: 2px solid #191970;
    }

        .button:hover {
            background-color: #D3D3D3
        }

        .button:active {
            background-color: #A9A9A9;
            transform: translateY(2px);
        }
</style>
<div>
    <hr />
    <div style="margin-top: 60px; display: -webkit-flex;">
        @* imagem do jogo *@
        <div style="border:solid; border-color:black;">
            <a href="~/ImagemCapas/@Model.Fotografia" target="_blank">
                <img src="~/ImagemCapas/@Model.Fotografia" width="400" height="487" />
            </a>
        </div>

        <div style="height:400px">
            @* nome do jogo *@
            <div style="color: red; font-family: 'Lucida Console'; text-align: left; font-size:47px; font-weight: bold; margin-top: -10px; margin-left: 20px; width: 100%;">
                @Html.DisplayFor(model => model.Titulo)
            </div>
            @* enredo do jogo *@
            <div style="font-family:'Lucida Console'; font-size:16.5px; color:white; text-align:justify; margin-left:20px;">
                @Html.DisplayFor(model => model.Resumo)
            </div>
            @* plataformas do jogo *@
            <div style="font-family:'Lucida Console';font-size: 25px; color: red; font-weight: bold;padding-top: 16px; margin-left:20px;">Plataformas</div>
            <div style="font-family:'Lucida Console'; font-size: 18px; color: black;text-align:justify; padding-top:2px; margin-left:20px;">
                @if (Model.ListaDePlataformas.Count() > 0)
                {
                    foreach (var plataforma in Model.ListaDePlataformas)
                    {
                        <a href="~/ImagemPlat/@Model.Logotipo" target="_blank">
                            <img src="~/ImagemPlat/@plataforma.Logotipo" width="130" height="100" />
                        </a>
                    }
                }
            </div>
        </div>
    </div>
</div>
@* personagens do jogo *@
<div style="font-family:Arial;font-size: 30px; color: red; font-weight: bold;padding-top: 56px; margin-left:6px;">Personagens</div>
<div style=" display:flex; flex-wrap:wrap; flex-direction:row; justify-content:space-around; align-content:center; margin-top: -4px;">
    @if (Model.ListaDePersonagens.Count() > 0)
    {
        foreach (var personagem in Model.ListaDePersonagens)
        {
            <div style="padding-top: 15px">
                <a href="~/Personagens/Details/@personagem.ID">
                    <img src="~/ImagemPers/@personagem.Fotografia" width="150" height="160" />
                </a>
            </div>
        }
    }
</div>
@* botões de editar a personagem somente para o administrador *@
@if (User.IsInRole("Admin"))
{
    <div class="btn-group" role="group" style="margin-bottom:9px; margin-top:20px; padding-left: 855px;">
        <button type="button" class="button" onclick="location.href='@Url.Action("Edit","Jogos", new { id=Model.ID })'">Editar jogo</button>
        <button type="button" class="button" onclick="location.href='@Url.Action("Delete","Jogos", new { id=Model.ID })'">Apagar jogo</button>
    </div>
}

@* botão para voltar à lista de jogos *@
<div class="btn-group" role="group" style="margin-bottom:9px; padding-top:10px; padding-left: 855px;">
    <button type="button" class="button" onclick="location.href='@Url.Action("Index","Jogos",new { id=Model.ID })'">Voltar para a lista de Jogos</button>
</div>

<div>
    <div class="text-center" style="margin-top:100px">
        <h1 class="comentarios" style="color: cadetblue">Comentários:</h1>
    </div>
    <hr class="estilo3">
    @if (!User.Identity.IsAuthenticated)
    {
        <div class="alert alert-info" style="margin-top:20px; margin-right:690px">
            <strong>Nota:</strong> Para adicionar um comentário é necessário iniciar sessão!
        </div>
    }

    else
    {
        <div style="margin-top:30px">
            @using (Html.BeginForm("Create", "Comentarios", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("JogoFK", Model.ID)
                @Html.Hidden("Username", User.Identity.Name)
                @Html.TextArea("Texto", "", 4, 100, htmlAttributes: new { @placeholder = "Adicione um Comentário" })
                <button type="submit" name=" botaoComentario" class="btn btn-primary "> Comentar </button>
            }
        </div>
    }
    @foreach (var comentario in Model.ListaDeComentarios)
    {

        <dt style="color:white; font-family:'Lucida Console'; font-size:15px;">
            <img src="~/ImagemUser/ImagemUser.jpg" width="30" height="30" />
            @Html.DisplayFor(c => comentario.Utilizadores.UserName)
        </dt>

        <dd style="color:white; font-family:'Lucida Console'; font-size:12px;">
            @Html.DisplayFor(c => comentario.Texto) -
            @Html.DisplayFor(c => comentario.DataComentario)
            @if (User.Identity.Name.Equals(comentario.Utilizadores.UserName) || User.IsInRole("Admin"))
            {
                <a href='@Url.Action("Delete", "Comentarios", new { id = comentario.ID, JogoFK = comentario.JogoFK })'>
                    <i class="glyphicon glyphicon-remove-sign" style="color:red;width:50px;height:50px"></i>
                </a>
            }

            @if (User.Identity.Name.Equals(comentario.Utilizadores.UserName)) {
                <a href='@Url.Action("Edit", "Comentarios", new { id = comentario.ID, JogoFK = comentario.JogoFK })' class="glyphicon  glyphicon-pencil">
                </a>
            }

        </dd>


    }
</div>

TekkenGame/TekkenGame/Views/Jogos/Index.cshtml
@model IEnumerable<TekkenGame.Models.Jogos>

@{
    ViewBag.Title = "Jogos";
}

<style>
        body {
            background-image: url(../../Fundos/Fundo3.jpg);
        }
</style>

<div style="font-family: 'Lucida Console'; text-align: left;color: red; font-size: 40px;font-weight: bold; margin-left:280px; margin-top:40px;">
    Conheça todos os jogos!
</div>
    
<div style=" display:flex; flex-wrap:wrap; flex-direction:row; justify-content:space-around; align-content:center; margin-top:30px;">
    @foreach (var item in Model)
    {
        <div style="padding-top: 15px">
            <a href="~/Jogos/Details/@item.ID">
                <img src="~/ImagemCapas/@item.Fotografia" width="300" height="360" />
            </a>
        </div>
    }
    </div>

<p>
    @if (User.IsInRole("Admin"))
    {
        @Html.ActionLink("Adicionar novo jogo", "Create")
    }
</p>